CREATE TABLE `email_templates` (
  `id` int(11) NOT NULL,
  `template_name` varchar(500) NOT NULL,
  `slug` varchar(600) NOT NULL,
  `template_variables` varchar(1000) NOT NULL,
  `template_content` text NOT NULL,
  `updated_by` int(11) NOT NULL,
  `updated_on` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `email_templates`
--

INSERT INTO `email_templates` (`id`, `template_name`, `slug`, `template_variables`, `template_content`, `updated_by`, `updated_on`) VALUES
(1, 'Forgot Password', 'forgot_password', '{fullname},{reset_link}', '<p>Hello {fullname}!</p><p>Follow the below link to Reset Your Password. </p><p>{reset_link}</p>', 1, '2020-04-11 07:41:25'),
(2, 'Reset Password', 'reset_password', '{fullname}', '<p>Hello {fullname}!</p><p>Your Password is successfully Reset.', 1, '2020-03-13 00:00:00'),
(3, 'Registration', 'registration', '{fullname},{activation_code},{activation_button}', '<p>Hello {fullname}!</p><p>You are successfully registered. Your activation code is. </p><h4>{activation_code}</h4>\r\n<p>{activation_button}</p>', 1, '2020-04-11 08:35:38'),
(4, 'New Ticket', 'new_ticket', '{sitename},{fullname},{ticket_title},{ticket_description}', '<p>Hello {sitename}!</p><p>A new ticket generated by {fullname}. </p><h4>{ticket_title}</h4><p>{ticket_description}</p>', 1, '2020-04-11 08:43:41'),
(5, 'Contact Form', 'site_contact', '{sitename},{fullname},{subject},{email},{message}', '<p>Hello {sitename}!</p><p>You have message from {fullname},</p><p>Subject : {subject},</p><p>Email : <a href=\"mailto:{email}\">{email}</a><br>Message: {message}<br></p>', 1, '2020-04-11 08:50:14'),
(6, 'Reply to Ticket', 'reply_ticket', '{fullname},{ticket_title},{reply_content}', '<p>Hello {fullname}!</p><p>You have reply for a Ticket. </p><h4>{ticket_title}</h4><p>{reply_content}</p>', 1, '2020-04-11 08:58:05'),
(7, 'Ticket Assigned', 'assign_ticket', '{fullname},{ticket_title},{ticket_description}', '<p>Hello {fullname}!</p><p>You have assigned with a Ticket. </p><h4>{ticket_title}</h4><p>{ticket_description}</p>', 1, '2020-04-08 12:38:53'),
(8, 'New User', 'user_creation', '{fullname},{sitename},{password}', '<p>Hello {fullname}!</p><p>You have registered in {sitename}</p><p>You can access the application to below password:</p><h3>{password}</h3>', 1, '2020-04-11 09:18:29');

--
-- Indexes for table `email_templates`
--
ALTER TABLE `email_templates`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `email_templates`
--
ALTER TABLE `email_templates`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- Dumping data for table `permissions`
--

INSERT INTO `permissions` (`id`, `permission_name`, `permission_slug`, `permission_info`, `updated_on`) VALUES
(50, 'Email Settings', 'email_settings', 'Manage Email Settings', '2020-03-13 00:00:00'),
(51, 'Email Templates', 'email_templates', 'Manage Email Templates', '2020-03-13 00:00:00');

--
-- Dumping data for table `role_permissions`
--

INSERT INTO `role_permissions` (`id`, `role_id`, `permission_id`, `is_permitted`, `updated_on`) VALUES
(99, 2, 50, 0, '2020-04-08 13:20:37'),
(100, 2, 51, 0, '2020-04-11 13:20:37'),
(101, 3, 50, 0, '2020-04-11 13:22:11'),
(102, 3, 51, 0, '2020-04-11 13:22:11');

--
-- Dumping data for table `config`
--

INSERT INTO `config` (`id`, `config_type`, `config_name`, `config_value`, `updated_on`) VALUES
(21, 'app', 'email_notify_reply_ticket', '1', '2020-02-18 00:00:00'),
(22, 'email', 'mail_from_email', 'noreply@truecoder.in', '2020-04-11 07:50:21'),
(23, 'email', 'mail_host', 'mail.truecoder.in', '2020-04-11 07:50:21'),
(24, 'email', 'mail_username', '_mailer@truecoder.in', '2020-04-11 07:50:21'),
(25, 'email', 'mail_port', '465', '2020-04-11 07:50:21'),
(26, 'email', 'mail_password', '1234567890', '2020-04-11 07:50:21'),
(27, 'email', 'mail_encryption', 'SSL', '2020-04-11 07:50:21'),
(28, 'email', 'mail_driver', 'MAIL', '2020-04-11 07:50:21'),
(29, 'email', 'mail_from_title', 'TrueSupport', '2020-04-11 07:50:21');